services:
  - type: web
    name: spring-boot-backend
    env: docker
    buildCommand: ./mvnw clean package -DskipTests  # Construcci칩n de la aplicaci칩n con Maven
    startCommand: java -jar target/*.jar           # Comando para ejecutar el archivo .jar generado
    git:
      branch: main  # Rama del repositorio de GitHub que deseas desplegar (puedes cambiar 'main' si es necesario)
      repo: https://github.com/dsanchezchu/megalabs-api.git  # URL de tu repositorio en GitHub
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod   # Puedes cambiar esto si tienes diferentes perfiles de Spring
    autoDeploy: true  # Activa la opci칩n para despliegues autom치ticos cuando haya cambios en el repositorio