spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${CORREO}
    password: ${PASSWORD_CORREO}
    port: ${PORT_CORREO}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false